version: '3.8'

services:
  ml_calorie_predictor:
    build:
      context: .  # Uses root directory as build context
      dockerfile: infra/docker/services/ml_calorie_prediction/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml_features/ml_calorie_estimation/mlruns:/app/ml_features/ml_calorie_estimation/mlruns
      - ./ml_features/ml_calorie_estimation/feature_store:/app/ml_features/ml_calorie_estimation/feature_store
    environment:
      - PYTHONPATH=/app
      - ML_PROJECT_ROOT=/app/ml_features/ml_calorie_estimation
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "ls -la /app/ml_features/ml_calorie_estimation/mlruns &&
             uvicorn ml_features.ml_calorie_estimation.pipeline.predict:app --host 0.0.0.0 --port 8000"
