version: '3.8'

services:
  ml_calorie_predictor:
    build:
      context: .  # Uses root directory as build context
      dockerfile: infra/docker/services/ml_calorie_prediction/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml_features/ml_calorie_estimation/mlruns:/app/ml_features/ml_calorie_estimation/mlruns
    environment:
      - PYTHONPATH=/app
      - ML_PROJECT_ROOT=/app/ml_features/ml_calorie_estimation
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3