collection:
  target_recipes: 2000
  min_recipes_per_category: 100
  requests_per_minute: 10
  max_retries: 3

api:
  base_url: "https://api.edamam.com/api/recipes/v2"
  timeout: 30

database:
  username: "iifymate"
  host: "localhost"
  database: "recipe_data"
