name: Deploy New Model to EC2

on:
    workflow_dispatch:
      inputs:
        model_data:
          description: 'JSON dictionary with model versions and S3 paths'
          required: true
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Deployment Request to EC2
        run: |
          echo "🔹 Raw model_data input: ${{ github.event.inputs.model_data }}"
          
          # Properly escape JSON before sending to webhook
          ESCAPED_JSON=$(echo '${{ github.event.inputs.model_data }}' | jq -c . | sed 's/"/\\"/g')

          curl -X POST "http://34.227.104.121:8003/update_model" \
            -H "Content-Type: application/json" \
            -d "{\"model_data\": $ESCAPED_JSON}"